---
title: "Conflict Events in Kenya from 1997 to 2020"
output: 
  flexdashboard::flex_dashboard:
    
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(DT)
library(dygraphs)
library(xts)
library(leaflet)
library(rgdal)
library(dplyr)
library(scales)
library(glue)
library(rmarkdown)
library(sf)
library(ggplot2)
```

```{r}
```
 column {data-width=200 .sidebar}
-----------------------------------------------------------------------
```{r, echo=FALSE}
data <- read.csv("Conflict_Kenya.csv")
sums <- read.csv("Conflict_Sums.csv")


selectInput(
  "Year",
  "Choose year:",
  choices = c("All Years", sort(unique(data$year))),
  multiple = FALSE,
  selected = "1997",
)

mydata<- reactive({
  if("1997" %in% input$year){
    data
    
  }else{
    filter(data, year %in% input$year)
  }
})
```
Conflict events in Kenya since 1997 visualization. The data is sourced from The Armed Conflict Location & Event Data Project https://acleddata.com/. Flexdashboard package was used to design the layout of the dashboard while R Shiny package was used to enable interactivity.

Column {data-width=650}
-----------------------------------------------------------------------

### Map

```{r}
data <- read.csv("Conflict_Kenya.csv")
sums <- read.csv("Conflict_Sums.csv")
mydata<- reactive({
 if("All Years" %in% input$Year){
   data
     
 }else{
   filter(data, year %in% input$Year)
 }
})
mypal <- reactive({
  leaflet::colorFactor (palette = "Red", domain = mydata()$event_type)
})
mypopups <-reactive({
  glue::glue("DATE: {mydata()$DATE}<BR />Location: {mydata()$Country}<br />Event Type: {mydata()$event_type}<br />Actor 1: {mydata()$actor1}<br />Actor 2: {mydata()$actor2}<br />Fatalities: {mydata()$fatalities}")
  })
  
leaflet::renderLeaflet({

  m <- leaflet(mydata()) %>% 
    addProviderTiles(providers$CartoDB.DarkMatter) %>% 
     addCircleMarkers(fillColor = ~mypal()(mydata()$event_type), radius = 2, color = "red", stroke = FALSE, fillOpacity = 0.9, popup = mypopups())
})


observeEvent(input$year,{
  leafletProxy("map", mydata()) %>% 
    addTiles() %>% 
          clearMarkers() %>% 
          addCircleMarkers(~`long`,
                           ~`lat`
                           ,radius = 2, color = "red", stroke = FALSE, fillOpacity = 0.9)
        })

```



Column {data-width=350}
-----------------------------------------------------------------------
### Timetrend
```{r}
data <- read.csv("Conflict_Kenya.csv")
renderDygraph({
  dygraph(sums)
})
```

### Data Table
```{r}
data <- read.csv("Conflict_Kenya.csv")
sums <- read.csv("Conflict_Sums.csv")
renderDT({
  datatable(mydata(), filter = c("none"), options = list(
    autoWidth = TRUE, xScroll = TRUE,
    columnDefs = list(list(width = '200px', targets = c(2, 4))),
    drop = FALSE
  ))
})
```

